### ISSUE TITLE
我就呵呵了，问题根本没解决，不停的滑动拉伸的首部，就会崩溃

### ISSUE THREAD

**Issue by lijuncai** [MarkMjw/PullScrollView#14]
也不知道你是怎么测试的，我还以为解决了，又下了一遍，高频率的滑动拉伸模块，就会崩溃

**Comment by msdx** [comment]
= =!
贴一下日志吧。
我这边用P7， 华为3C，以及酷派，也快速地滑动了，真没测出来。

**Comment by lijuncai** [comment]
05-29 00:35:33.833    1293-1293/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.IllegalArgumentException: pointerIndex out of range
            at android.view.MotionEvent.nativeGetAxisValue(Native Method)
            at android.view.MotionEvent.getY(MotionEvent.java:2160)
            at android.widget.ScrollView.onTouchEvent(ScrollView.java:854)
            at com.markmao.pullscrollview.ui.widget.PullScrollView.onTouchEvent(PullScrollView.java:164)
            at android.view.View.dispatchTouchEvent(View.java:7234)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2231)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1964)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2237)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1979)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2237)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1979)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2237)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1979)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2237)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1979)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2165)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1481)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2469)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2113)
            at android.view.View.dispatchPointerEvent(View.java:7414)
            at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3524)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3456)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4566)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4544)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4648)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
            at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
            at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:163)
            at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:4616)
            at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:4667)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
            at android.view.Choreographer.doCallbacks(Choreographer.java:555)
            at android.view.Choreographer.doFrame(Choreographer.java:523)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4963)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by lijuncai** [comment]
不停的拉，还会多出一块白块

**Comment by lijuncai** [comment]
呵呵，自己没测出来，就认为没问题，把问题关闭，还呵呵我，也是牛逼

**Comment by msdx** [comment]
呵呵，又不贴日志，就在那里吼，跟小白用户一样，这样也是程序员，也是牛逼。

**Comment by lijuncai** [comment]
我叫什么了，我说程序会崩溃，小白用户怎么了，没小白用户，你喝西北风啊，真能装逼

**Comment by msdx** [comment]
叫程序会崩溃，什么描述都没有，有用？谁知道是不是你自己的问题。没你能装逼。

**Comment by msdx** [comment]
用小白用户来形容你还真污辱了小白，小白还知道描述一下问题出现的过程和环境。

**Comment by lijuncai** [comment]
还有我贴了日志，看不到，不去调试问题，就在这胡编乱找，真是搞笑，我没描述？太逗了，呵呵，你要认为自己的代码完美，再把问题关了，就可以，如果这份代码的主人和你一个德行，我也没兴趣，再提issue

**Comment by lijuncai** [comment]
自己测过就认为没问题的，这种自大的程序员，真实让人佩服，称你为程序员，真实侮辱

**Comment by msdx** [comment]
关的是你第一个issue，你第一个issue有贴日志？你这个issue贴了日志的，我有说关掉这个issue?

**Comment by msdx** [comment]
你这种素质，也让人大开眼界，这样的人，在github上看到你也真是对github的侮辱

**Comment by lijuncai** [comment]
你给我机会贴日志了？代码主人不搭理我，我贴什么日志？

**Comment by lijuncai** [comment]
对，哈哈，这样的人看到我，确实是对github的侮辱，别人提的issue，不问别人就关掉，就已一句测过没问题，这么自大的人，我也是第一次见，既然你已经开始人身攻击，我也不浪费口舌了，自己玩去吧，再见

**Comment by fashioncj** [comment]
诶。。突然看到撕逼也是最了。。。这个可以自己fix的吧。。毕竟是代码而且错误信息都有了。

**Comment by lijuncai** [comment]
嗯，我改的另一份的，本来我也懒得理他，不过实在太自以为是

**Comment by ximencx** [comment]
用别人的代码  还撕逼 人品有问题啊

**Comment by msdx** [comment]
@ximencx 嗯，你说得对。以前不懂事，难免处事不当，也是吃一堑长一智。人孰无过，这是我的第一次，也是我的最后一次。

**Comment by chenzheng8975** [comment]
too young too simple
